### ISSUE TITLE
Linking to additional area by area deprivation data

### ISSUE THREAD

**Issue by HeatherARobinson** [RUMgroup/brexit_data_challenge#3]
File 2 at https://www.gov.uk/government/statistics/english-indices-of-deprivation-2015 gives a breakdown of the 2005 indices of multiple deprivation for each LSOA, including healthcare provision, employment, crime and access to social housing.  These will be good variables to include in our models.  Have a go at adding this onto your table using the merge() command described at https://www.statmethods.net/management/merging.html.

**Comment by HeatherARobinson** [comment]
'geographycode' in the table provided in the challenge folder appears to be LSOA.

**Comment by Cdevenish** [comment]
And the brexit data is by Local Authority (Area_Code), so I guess we'll have to aggregate ethnicity to Local Authority to be able to compare to brexit vote.

**Comment by langtonhugh** [comment]
I don't know about yearly changes is boundaries, but I think this is the relevant look up table for that. It should include the nesting of LSOA / ward / local authority: 

http://geoportal.statistics.gov.uk/datasets/lower-layer-super-output-area-2011-to-ward-2016-lookup-in-england-and-wales
